# mainLogger with interceptors for ometers
log4j.category.mainLogger=DEBUG, FILE
log4j.additivity.mainLogger=false

log4j.appender.FILE=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FILE.File=/opt/BBS/logs/maintenance/ts_idp_nemid.log
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} [TID=%X{TID}] [%p] [%c] %m%n

